export default {
  name: "school",
  title: "Schools",
  type: "document",
  fields: [
    {
      name: "name",
      title: "Name",
      type: "string",
      validation: (Rule) => Rule.required(),
    },
    {
      name: "city",
      title: "City",
      type: "string",
    },
    {
      name: "location",
      title: "State/Location",
      type: "string",
      description:
        "If your school is in a location not listed here, please contact us and we will add it!",
      options: {
        list: [
          { value: "Alabama", title: "Alabama" },
          { value: "Alaska", title: "Alaska" },
          { value: "Arizona", title: "Arizona" },
          { value: "Arkansas", title: "Arkansas" },
          { value: "California", title: "California" },
          { value: "Colorado", title: "Colorado" },
          { value: "Connecticut", title: "Connecticut" },
          { value: "Delaware", title: "Delaware" },
          { value: "Florida", title: "Florida" },
          { value: "Georgia", title: "Georgia" },
          { value: "Hawaii", title: "Hawaii" },
          { value: "Idaho", title: "Idaho" },
          { value: "Illinois", title: "Illinois" },
          { value: "Indiana", title: "Indiana" },
          { value: "Iowa", title: "Iowa" },
          { value: "Kansas", title: "Kansas" },
          { value: "Kentucky", title: "Kentucky" },
          { value: "Louisiana", title: "Louisiana" },
          { value: "Maine", title: "Maine" },
          { value: "Maryland", title: "Maryland" },
          { value: "Massachusetts", title: "Massachusetts" },
          { value: "Michigan", title: "Michigan" },
          { value: "Minnesota", title: "Minnesota" },
          { value: "Mississippi", title: "Mississippi" },
          { value: "Missouri", title: "Missouri" },
          { value: "Montana", title: "Montana" },
          { value: "Nebraska", title: "Nebraska" },
          { value: "Nevada", title: "Nevada" },
          { value: "New Hampshire", title: "New Hampshire" },
          { value: "New Jersey", title: "New Jersey" },
          { value: "New Mexico", title: "New Mexico" },
          { value: "New York", title: "New York" },
          { value: "North Carolina", title: "North Carolina" },
          { value: "North Dakota", title: "North Dakota" },
          { value: "Ohio", title: "Ohio" },
          { value: "Oklahoma", title: "Oklahoma" },
          { value: "Oregon", title: "Oregon" },
          { value: "Pennsylvania", title: "Pennsylvania" },
          { value: "Rhode Island", title: "Rhode Island" },
          { value: "South Carolina", title: "South Carolina" },
          { value: "South Dakota", title: "South Dakota" },
          { value: "Tennessee", title: "Tennessee" },
          { value: "Texas", title: "Texas" },
          { value: "Utah", title: "Utah" },
          { value: "Vermont", title: "Vermont" },
          { value: "Virginia", title: "Virginia" },
          { value: "Washington", title: "Washington" },
          { value: "West Virginia", title: "West Virginia" },
          { value: "Wisconsin", title: "Wisconsin" },
          { value: "Wyoming", title: "Wyoming" },
          { value: "Taiwan", title: "Taiwan" },
        ],
      },
      validation: (Rule) => Rule.required(),
    },
    {
      name: "grade",
      title: "Grade Level",
      type: "string",
      options: {
        list: ["High School", "8th Grade"],
      },
    },
  ],
};
